package pageObject;

import org.openqa.selenium.By;
import org.openqa.selenium.support.PageFactory;
import utilities.Driver;

public class mainPageElements {
    public mainPageElements(){PageFactory.initElements(Driver.getDriver(),this);}
    public final By clickNeden = By.xpath("//li[@id='menu-item-31740']");
    public final By clickAstronomi = By.xpath("//li[@id='menu-item-30340']");
    public final By clickFizik = By.xpath("//li[@id='menu-item-30349']");
    public final By clickKimya = By.xpath("//li[@id='menu-item-31794']");
    public final By clickBiyoloji = By.xpath("//li[@id='menu-item-31799']");
    public final By clickDiger = By.xpath("//li[@id='menu-item-31827']");
    public final By clickNasil = By.xpath("//li[@id='menu-item-31623']");
    public final By clickSavunma = By.xpath("//li[@id='menu-item-31826']");
    public final By clickOtomotiv = By.xpath("//li[@id='menu-item-31837']");
    public final By clickEnerji = By.xpath("//li[@id='menu-item-31858']");
    public final By clickYapayZeka = By.xpath("//li[@id='menu-item-31870']");
    public final By clickElektronik = By.xpath("//li[@id='menu-item-31875']");
    public final By clickBilgisayar = By.xpath("//li[@id='menu-item-31884']");
    public final By clickGuvenlik = By.xpath("//li[@id='menu-item-31905']");
    public final By clickUzayHavacilik = By.xpath("//li[@id='menu-item-31912']");
    public final By clickIsDunyasi = By.xpath("//li[@id='menu-item-31632']");
    public final By clickTurkiye = By.xpath("//li[@id='menu-item-31920']");
    public final By clickDunya = By.xpath("//li[@id='menu-item-31923']");
    public final By clickYasam = By.xpath("//li[@id='menu-item-31629']");
    public final By clickSaglik = By.xpath("//li[@id='menu-item-31933']");
    public final By clickEgitim = By.xpath("//li[@id='menu-item-31940']");
    public final By clickCevre = By.xpath("//li[@id='menu-item-31947']");
    public final By clickKultur = By.xpath("//li[@id='menu-item-31954']");
    public final By clickOyun = By.xpath("//li[@id='menu-item-31961']");
    public final By clickSpor = By.xpath("//li[@id='menu-item-31972']");
    public final By clickDarkMode = By.xpath("//div[@data-mode='second']");
    public final By clickSunMode = By.xpath("//div[@data-mode='main']");
    public final By clickMenuBar = By.xpath("//div[@data-id='68c46803']");
    public final By clickNedenInMenuBar = By.xpath("//ul[@id='menu-1-68c46803' ]//a[contains(., 'Neden')]");
    public final By clickAstronomiInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Astronomi')]");
    public final By clickFizikInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Fizik')]");
    public final By clickKimyaInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Kimya')]");
    public final By clickBiyolojiInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Biyoloji')]");
    public final By clickDigerInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Diğer')]");
    public final By clickNasilInMenuBar = By.xpath("//ul[@id='menu-1-68c46803' ]//a[contains(., 'Nasıl')]");
    public final By clickSavunmaInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Savunma')]");
    public final By clickOtomotivInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Otomotiv')]");
    public final By clickEnerjiInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Enerji')]");
    public final By clickYapayZekaInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Yapay Zeka')]");
    public final By clickElektronikInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Elektronik')]");
    public final By clickBilgisayarInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Bilgisayar')]");
    public final By clickGuvenlikInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Güvenlik')]");
    public final By clickUzayHavacilikInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Uzay / Havacılık')]");
    public final By clickIsDunyasiInMenuBar = By.xpath("//ul[@id='menu-1-68c46803' ]//a[contains(., 'İş Dünyası')]");
    public final By clickTurkiyeInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Türkiye')]");
    public final By clickDunyaInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Dünya')]");
    public final By clickYasamInMenuBar = By.xpath("//ul[@id='menu-1-68c46803' ]//a[contains(., 'Yaşam')]");
    public final By clickSaglikInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Sağlık')]");
    public final By clickEgitimInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Eğitim')]");
    public final By clickCevreInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Çevre')]");
    public final By clickKulturInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Kültür')]");
    public final By clickOyunInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Oyun')]");
    public final By clickSporInMenuBar = By.xpath("//ul[@class='sub-menu' ]//a[contains(., 'Spor')]");
    public final By clickInstagramInMenuBar = By.xpath("//div[@data-id='37710469']//a[@href='https://www.instagram.com/2n_news/']");
    public final By clickFacebookInMenuBar = By.xpath("//div[@data-id='37710469']//a[@href='https://www.facebook.com/2nnews']");
    public final By clickTwitterInMenuBar = By.xpath("//div[@data-id='37710469']//a[@href='https://x.com/2n_news']");
    public final By clickYoutubeInMenuBar = By.xpath("//div[@data-id='37710469']//a[@href='https://www.youtube.com/@2n_news']");
    public final By clickTiktokInMenuBar = By.xpath("//div[@data-id='37710469']//a[@href='https://www.tiktok.com/@2n_news']");
    public final By clickLinkedInInMenuBar = By.xpath("//div[@data-id='37710469']//a[@href='https://www.linkedin.com/company/2nn-news/']");
    public final By clickHakkimizda = By.xpath("//ul[@id='menu-1-8752bdc']//a[contains(., 'Hakkımızda')]");
    public final By clickKunye = By.xpath("//ul[@id='menu-1-8752bdc']//a[contains(., 'Künye')]");
    public final By clickIletisim = By.xpath("//ul[@id='menu-1-8752bdc']//a[contains(., 'İletişim')]");
    public final By clickGizlilkIlkeleri = By.xpath("//ul[@id='menu-1-1d73422']//a[contains(., 'Gizlilik İlkeleri')]");
    public final By clickCerezPolitikasi = By.xpath("//ul[@id='menu-1-1d73422']//a[contains(., 'Çerez Politikası')]");
    public final By clickAydinlatmaMetni = By.xpath("//ul[@id='menu-1-1d73422']//a[contains(., 'Aydınlatma Metni')]");
    public final By clickInstagramInMainPage = By.xpath("//div[@data-id='4c06b6b0']//a[@href='https://www.instagram.com/2n_news/']");
    public final By clickFacebookInMainPage = By.xpath("//div[@data-id='4c06b6b0']//a[@href='https://www.facebook.com/2nnews']");
    public final By clickTwitterInMainPage = By.xpath("//div[@data-id='4c06b6b0']//a[@href='https://x.com/2n_news']");
    public final By clickYoutubeInMainPage = By.xpath("//div[@data-id='4c06b6b0']//a[@href='https://www.youtube.com/@2n_news']");
    public final By clickTiktokInMainPage = By.xpath("//div[@data-id='4c06b6b0']//a[@href='https://www.tiktok.com/@2n_news']");
    public final By clickLinkedInInMainPage = By.xpath("//div[@data-id='4c06b6b0']//a[@href='https://www.linkedin.com/company/2nn-news/']");
    public final By clickGetMainPageButton = By.xpath("//i[@class='cmsdemo-icon- cms-demo-icon-arrow-up']");

}
